language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install coverage==4.5.4
  - pip install flake8 pytest-cov pyDOE coveralls python-coveralls
  - pip install pytest --upgrade
  - pip install . --no-cache-dir
script:
  - pytest --cov=pwlf -p no:warnings tests/tests.py
before_script:
  - flake8 pwlf
  - pytest --version
after_success:
  - coveralls
